spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: 1234

org:
  gradle:
    jvmargs: "-Xmx512m -XX:MaxPermSize=256m"
    daemon: true
    parallel: true
    caching: true
